### ISSUE TITLE
Error, unknown cone property

### ISSUE THREAD

**Issue by alfsan** [gap-packages/NormalizInterface#62] opened 2019-07-03 19:53 UTC
Using NmzPrintConeProperties I get an error message. Here it is the session transcription:

```
gap> M := [
> [  1,  1,  2 ],
> [ -1, -1,  3 ],
> [  1, -2,  4 ],
> ];;
gap> gr := [ [ 0, 0, 1 ] ];;
gap> cone := NmzCone(["integral_closure", M, "grading", gr]);;
gap> NmzCompute(cone);
true
gap> NmzPrintConeProperties(cone);
Generators = 
[ [   1,   1,   2 ],
  [  -1,  -1,   3 ],
  [   1,  -2,   4 ] ]
ExtremeRays = 
[ [   1,   1,   2 ],
  [  -1,  -1,   3 ],
  [   1,  -2,   4 ] ]
SupportHyperplanes = 
[ [  -8,   2,   3 ],
  [   1,  -1,   0 ],
  [   2,   7,   3 ] ]
HilbertBasis = 
[ [   0,   0,   1 ],
  [   1,   1,   2 ],
  [  -1,  -1,   3 ],
  [   0,  -1,   3 ],
  [   1,   0,   3 ],
  [   1,  -2,   4 ],
  [   1,  -1,   4 ],
  [   0,  -2,   5 ] ]
Deg1Elements = 
[ [  0,  0,  1 ] ]
OriginalMonoidGenerators = 
[ [   1,   1,   2 ],
  [  -1,  -1,   3 ],
  [   1,  -2,   4 ] ]
MaximalSubspace = [  ]
Grading = [ 0, 0, 1 ]
ClassGroup = [ 0, 3, 15 ]
TriangulationDetSum = 15
GradingDenom = 1
UnitGroupIndex = 1
InternalIndex = 15
Multiplicity = 5/8
TriangulationSize = 1
Error, unknown cone property in
  result := _NmzConeProperty( cone, prop ); at /home/alfredo/lib/gap-4.10.1/pkg/NormalizInterface-1.0.2/lib/normaliz.gi:13 called from 
NmzConeProperty( cone, prop ) at /home/alfredo/lib/gap-4.10.1/pkg/NormalizInterface-1.0.2/lib/normaliz.gi:47 called from
<function "NmzPrintConeProperties">( <arguments> )
 called from read-eval loop at *stdin*:67
```
Tnank you,

Alfredo

**Comment by fingolfin** [comment] 2019-07-24 20:33
Which version of Normaliz are you using there? I can't reproduce this with Normaliz 3.4.0 as bundled with NormalizInterface; I suspect you are using a newer version (in which case PR #65 will help).

**Comment by fingolfin** [comment] 2019-07-24 20:34
In fact it should also be fixed on master, thanks to commit 906b93cb21380b619d42297ebdee16233eecf2d2 (which is just a tiny part of PR #65).

**Comment by kamalsaleh** [comment] 2019-07-24 21:35
I have already tested this example with the above commit https://github.com/gap-packages/NormalizInterface/commit/325c38f0ee1f93d82886fcc591d2b71e75f7f865 and the error is still raised. The property of the "nmz-cone" that is not available is the `NumberLatticePoints`, which should return the number of integral lattice points inside the "nmz-cone". This number is finite only if the "nmz-cone" is a mathematical polytope. In this example the input defines a  non-bounded cone which contains infinite number of lattice points. So it make sense that this property is not available. What I don't understand is why `"NumberLatticePoints"` belongs to `NmzKnownConeProperties(cone)`.

**Comment by fingolfin** [comment] 2019-07-24 21:38
@kamalsaleh that is a *different* error, and one you get because you are using a much, much newer version of Normaliz (>= 3.7.0) than the one shipped with NormalizInterface (and which thus never was tested with NormalizInterface). This is fixed by PR #65; but the issue @alfsan reports here should already be fixed on `master`, it already occurs with e.g. Normaliz 3.5.4

**Comment by kamalsaleh** [comment] 2019-07-24 22:04
100%

**Comment by alfsan** [comment] 2019-07-25 11:08
Perhaps this answer comes late: I am using Normaliz 3.7.3

**Comment by fingolfin** [comment] 2019-08-12 14:38
This is fixed in master

**Closed by fingolfin** 2019-08-12 14:38 UTC
Labels: bug
